### ISSUE TITLE
Can't import to Android-Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [hiq-larryschiefer/SimpleFractal#3]
This is what I get:

D:\android\Android studio Projects\SimpleFractal\src\com\hiqes\SimpleFractal\mand_gen.rs
Error:android-renderscript-compiler: Command "D:\android\Sdk\build-tools\23.0.1\llvm-rs-cc.exe -I D:\android\Sdk\build-tools\23.0.1\renderscript\clang-include\ -I D:\android\Sdk\build-tools\23.0.1\renderscript\include\ -p C:\Users\user.AndroidStudio1.4\system\compile-server_temp_\generated-rs-temp0.tmp -o C:\Users\user.AndroidStudio1.4\system\compile-server\simplefractal_8d75faec\targets\java-production\SimpleFractal\android\generated_resources\raw -target-api 23 -d C:\Users\user.AndroidStudio1.4\system\compile-server_temp_\generated-rs-temp0.tmp\com\hiqes\SimpleFractal -MD D:\android\Android studio Projects\SimpleFractal\src\com\hiqes\SimpleFractal\mand_gen.rs" execution failed with exit code -1073741515
D:\android\Android studio Projects\SimpleFractal\src\com\hiqes\SimpleFractal\mand_float_gen.rs
Error:android-renderscript-compiler: Command "D:\android\Sdk\build-tools\23.0.1\llvm-rs-cc.exe -I D:\android\Sdk\build-tools\23.0.1\renderscript\clang-include\ -I D:\android\Sdk\build-tools\23.0.1\renderscript\include\ -p C:\Users\user.AndroidStudio1.4\system\compile-server_temp_\generated-rs-temp0.tmp -o C:\Users\user.AndroidStudio1.4\system\compile-server\simplefractal_8d75faec\targets\java-production\SimpleFractal\android\generated_resources\raw -target-api 23 -d C:\Users\user.AndroidStudio1.4\system\compile-server_temp_\generated-rs-temp0.tmp\com\hiqes\SimpleFractal -MD D:\android\Android studio Projects\SimpleFractal\src\com\hiqes\SimpleFractal\mand_float_gen.rs" execution failed with exit code -1073741515

**Comment by hiq-larryschiefer** [comment]
What branch did you check out and try to open/import?

**Comment by AndroidDeveloperLB** [comment]
I used this:
https://github.com/hiq-larryschiefer/SimpleFractal.git

**Comment by hiq-larryschiefer** [comment]
The master branch of the repo is still the original version of the project for Eclipse.  Try switching to the "migrate_as" branch, then import/open in Android Studio.  It was migrated to Android Studio some time ago, but it should still work with the latest version.

**Comment by AndroidDeveloperLB** [comment]
Which one should I use, then?

**Comment by hiq-larryschiefer** [comment]
migrate_as is the latest branch and the one which should be used.

**Comment by AndroidDeveloperLB** [comment]
You mean like this:

![untitled20151017004148](https://cloud.githubusercontent.com/assets/5357526/10554004/e92da6ca-7467-11e5-875d-4e07b58aed59.png)

?

**Comment by hiq-larryschiefer** [comment]
Yes, or clone via the command line or your GUI choice of tool and switch to that branch.

**Comment by AndroidDeveloperLB** [comment]
It still has issues. It wanted me to install old built tools, so I did, and now it says this error:

Gradle 'SimpleFractal-migrate_as' project refresh failed
Error:Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.4-all.zip'.

**Comment by AndroidDeveloperLB** [comment]
I think something is wrong with the sdk tools. Will re-install again.

**Comment by hiq-larryschiefer** [comment]
It could be the project, it's not been updated to the latest tools for quite some time. If I can get some time this weekend, I'll update it and push a new version.

**Comment by AndroidDeveloperLB** [comment]
I still failed. Even after updating the various versions, I get this error:

Error:Execution failed for task ':app:compileDebugNdk'.

> Error: NDK integration is deprecated in the current plugin.  Consider trying the new experimental plugin.  For details, see http://tools.android.com/tech-docs/new-build-system/gradle-experimental.  Set "android.useDeprecatedNdk=true" in gradle.properties to continue using the current NDK integration.

Where exactly should I put android.useDeprecatedNdk=true ?

**Comment by hiq-larryschiefer** [comment]
Try doing a fresh checkout and open in Android Studio.  Master branch is now up to date, merged the migrate_as branch into it.  You'll need to make sure you have the NDK tools installed via the Android SDK Manager.  Update local.properties to point to your correct SDK and NDK locations.  It's now updated to Android Studio 1.4, latest gradle plugin and tools.  It's still building NDK code in the "deprecated ndk build" mode since the full NDK integration is still in preview right now.

Verified it is building and able to run on Nexus 5 running Android 6.0.

**Comment by AndroidDeveloperLB** [comment]
Where do I set the NDK path? I don't see that you do it anywhere...
Also, how come the error that I get now has nothing to do with NDK ? This is what I get:

Error:Execution failed for task ':app:compileDebugRenderscript'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android\Sdk\build-tools\23.0.1\llvm-rs-cc.exe'' finished with non-zero exit value -1073741515

**Comment by hiq-larryschiefer** [comment]
You set the NDK path in the local.properties file.  There's a good chance Android Studio overwrote what was checked in as it is an auto-generated file and NDK support is somewhat weak.

As far as the llvm-rs-cc error you are seeing, I'm not sure what would be causing that.  The error number isn't real helpful.  Make sure that you have the Android compatibility libraries installed in your SDK.  The project does enable Renderscript compatibility modes, which will require those libs.

**Comment by AndroidDeveloperLB** [comment]
I have everything already updated:
![2015-10-19_232315](https://cloud.githubusercontent.com/assets/5357526/10590262/7497cac2-76b8-11e5-864c-29491deea868.png)

**Comment by hiq-larryschiefer** [comment]
Did your Android Studio setup make any changes to other files, such as build.gradle in the top level directory or under the app directory?

**Comment by hiq-larryschiefer** [comment]
Try this: inside of Android Studio, in the bottom left corner there should be a "Terminal" tab.  You may have to expand the tabs by clicking on a square in the lower left corner.  Once you have the terminal open, it should be in the top level directory of the project.  Run this:

`gradlew assembleDebug`

Paste the entire output into a comment here and I'll have a look.

**Comment by hiq-larryschiefer** [comment]
OK, hang on...seeing some build issues now w/merged master branch.  I'll try to resolve as I get some time.  Try the "migrate_as" branch for now instead of "master".

**Comment by hiq-larryschiefer** [comment]
OK, try 'master' now.  Verified I can build in AS as well as via the command line.  You'll still need to have `local.properties` setup correctly.  See the README for an example.

**Comment by AndroidDeveloperLB** [comment]
Sorry, I still get the same error.
Is the NDK a part of Android Studio now? I see it has a plugin, but does it need more?
I remember that for Eclipse, I had to set the path right withing Eclipse itself, to the installation path of this:
http://developer.android.com/ndk/downloads/index.html
But I can't find it on Android-Studio.

**Comment by hiq-larryschiefer** [comment]
No, NDK isn't part of Android Studio, you have to go into the SDK manager and install the "NDK Bundle" as I described in the updated README.  You'll also ned to have the file `local.properties` setup so it points to both the SDK location (automatically done by Android Studio) and the NDK directory.  It's in the updated README as well.

**Comment by hiq-larryschiefer** [comment]
OK, this is some type of issue with building on Windows.  I've been building with Android Studio on a Mac Book Pro and it works fine.  I see the same issue you do when building on Windows.  I'll see if there's an existing bug report on it with Google and if not I'll file one.  In the meantime, if you have a Mac or maybe even a Linux box, give that a try instead.

**Comment by hiq-larryschiefer** [comment]
Sure enough, there's a bug in the SDK packaging and it's been logged:
https://code.google.com/p/android/issues/detail?id=188096

(note the last comment: there is a workaround by copying some DLLs)

**Comment by AndroidDeveloperLB** [comment]
This is a post I wrote there :)

**Comment by hiq-larryschiefer** [comment]
:-)  Glad it was something with the tools and not the project!

**Comment by AndroidDeveloperLB** [comment]
Well I still want to try out the project. :(

**Comment by hiq-larryschiefer** [comment]
Did you try copying the DLLs as the bug report states as a work around?

**Comment by AndroidDeveloperLB** [comment]
Tried it now. It says this:

Error:Execution failed for task ':app:compileDebugNdk'.

> NDK not configured.
> Download the NDK from http://developer.android.com/tools/sdk/ndk/.Then add ndk.dir=path/to/ndk in local.properties.
> (On Windows, make sure you escape backslashes, e.g. C:\ndk rather than C:\ndk)

So I've added the path to local.properties file:
    ndk.dir=D:\android\Sdk\ndk 

But then I got this error:

D:\android\Sdk\ndk\build\core\add-application.mk
Error:(199) **\* Android NDK: Aborting...    .  Stop.
Error:Execution failed for task ':app:compileDebugNdk'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android\Sdk\ndk\ndk-build.cmd'' finished with non-zero exit value 2

**Comment by hiq-larryschiefer** [comment]
OK, that's something with your setup.  I was able to copy the DLLs as indicated in the bug report and it built on Windows.  Make sure you're using the NDK from the SDK tools, which gets installed in SDK\ndk-bundle.  With the latest tools (23.0.1 I believe) I could only get this to work with that NDK.  For some reason my stand-alone NDK install wouldn't work.

**Comment by AndroidDeveloperLB** [comment]
After updating various things on the project, it works:

```
    classpath 'com.android.tools.build:gradle:2.2.2'

compileSdkVersion 25
buildToolsVersion '23.0.3'

defaultConfig {
    minSdkVersion 14
    targetSdkVersion 25
```
