### ISSUE TITLE
Gradle version Problem [with solution]

### ISSUE THREAD

**Issue by AllBecomesGood** [hiq-larryschiefer/SimpleFractal#4]
Hi,
just downloaded this after watching your youtube video about it and Renderscript. 
Android Studio had a small issue with the Gradle version, but it was quickly overcome with the answer of piotrek1543 using gradle version 1.5.0 (http://stackoverflow.com/questions/34749299/gradle-version-2-2-is-required-current-version-is-2-10/35186295).

I thought I'd leave this here and also thanks to you for this!

**Comment by hiq-larryschiefer** [comment]
Thanks for the feedback on this!  I'll actually push out a new version of the build files for Android Studio 2.2 soon.
