### ISSUE TITLE
R.raw.mand_float_gen missing

### ISSUE THREAD

**Issue by nkarki** [hiq-larryschiefer/SimpleFractal#5]
Hi, 

MandelbrotRSFloatGen.java can't find the R.raw.mand_float_gen id. The raw folder doesn't seem to exist in the project as well which is probably why the id doesn't show up. I tried adding the folder but I don't know what value the id is supposed to have. Is there something missing in the source code or I am missing something?

Thanks!
Nishant

**Comment by hiq-larryschiefer** [comment]
Hi Nishant,

What branch are you building and what version of Android Studio are you using?  It's been a little while since the build files have been updated, so it's possible that a newer version of Android Studio may cause some build issues.

-Larry

**Comment by hiq-larryschiefer** [comment]
Looks like the latest Android Studio / gradle DSL generates the code differently and the ScriptC constructors are slightly different.  Updated the build files to support Android Studio 3.0 (Preview), beta 2.
